### ISSUE TITLE
MacOS version fails to do anything. 

### ISSUE THREAD

**Issue by darodi** [darodi/kcc#23]
> I've try the MacOS version, but it fail to do anything. I have to go back to the original DMG to start working.

Do you have more information about this? It would be better to fix it.
I don't own a mac os, I need to find a way to test this.

_Originally posted by @darodi in https://github.com/darodi/kcc/issues/21#issuecomment-1363999913_

**Comment by celogeek** [comment]
How can I provide useful debugging information?
I will try to see what I can do

**Comment by celogeek** [comment]
I can't open the last beta. The OS said it is damage. I try to right click open. Same.

**Comment by celogeek** [comment]
I've fix it with:
```
xattr -d com.apple.quarantine /Applications/Kindle\ Comic\ Converter.app
```

Testing

**Comment by celogeek** [comment]
I try a PDF. Kindle Scribe + EPUB 200. It works !!!
Trying CBR and CBZ...

**Comment by celogeek** [comment]
CBR failed: Error during conversion. So the RAR lib have trouble.

**Comment by celogeek** [comment]
CBZ failed too.

**Comment by celogeek** [comment]
Directory works.
I compare the ressource inside the App package, and it is exactly the same as the origin package (kcc).
So I guess something does't wrong between the bin KCC and the resource.

**Comment by celogeek** [comment]
I run otool on the KCC-Beta vs KCC:
First is your package. Second is the original.
And Resources is the same.
```
➜  MacOS otool -L Kindle\ Comic\ Converter
Kindle Comic Converter:
	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 165.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 56.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1856.105.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 1141.1.0)
➜  MacOS otool -L /Volumes/Kindle\ Comic\ Converter/Kindle\ Comic\ Converter.app/Contents/MacOS/Kindle\ Comic\ Converter
/Volumes/Kindle Comic Converter/Kindle Comic Converter.app/Contents/MacOS/Kindle Comic Converter:
	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 157.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 48.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1258.1.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 728.9.0)
```

**Comment by celogeek** [comment]
Also plist file is the same. You should probably update the version in it.
```
      <string>5.5.2</string>
        <key>CFBundleSignature</key>
        <string>????</string>
        <key>CFBundleVersion</key>
        <string>5.5.2</string>
```

**Comment by darodi** [comment]
in this version,

https://github.com/darodi/kcc/releases/download/v5.5.3-beta-darodi.2/KindleComicConverter_osx_5.5.3-beta-darodi.2.dmg

CookieCaptainD said he was able to create mobi files (and epub as they are needed by mobi files)

https://github.com/ciromattia/kcc/pull/405#issuecomment-1058947663

but no news about cbz,cbr,rar,zip

**Comment by darodi** [comment]
> I run otool on the KCC-Beta vs KCC: First is your package. Second is the original. And Resources is the same.
> 

I'm using the same method to build, and the files haven't changed

https://github.com/darodi/kcc/blob/65c329d49529da6cfde1dc0517e642ce24436810/setup.py#L39-L60

**Comment by celogeek** [comment]
I can create a epub, only from PDF or Directory with flat file.
The trouble is when I want to open the CBR or CBZ, which will require to use the 7z include in the package.
I succeed running it, so it seems to be compatible.

**Comment by celogeek** [comment]
Um, I would like to build this locally. I've got M1 arch.

**Comment by darodi** [comment]
> Also plist file is the same. You should probably update the version in it.
> 
> ```
>       <string>5.5.2</string>
>         <key>CFBundleSignature</key>
>         <string>????</string>
>         <key>CFBundleVersion</key>
>         <string>5.5.2</string>
> ```

done, see 4fbcb79b

**Comment by darodi** [comment]
I found a vagrant box with mac osx
https://app.vagrantup.com/amarcireau/boxes/macos

I need to make some space on my computer and then I'll be able to test this too.

** edit: won't work, it's not the same arch **

**Comment by celogeek** [comment]
After some debugging and manage to build the dmg on m1 arch (with python + qt native), I find out what's failed here.
the 7z which is used to unpack the files seems to have the wrong arch.
So the app start as a native m1 app, and failed to launch 7z.

I replace the 7z with p7zip file installed with brew on m1 arch.
Now PDF and CBZ works, but CBR still failed. 7z is not able to uncompress rar files.

Is is possible to replace the external tools 7z by a python uncompress lib (for zip, gzip and even rar) ? this way no need for an external tools.

**Comment by celogeek** [comment]
Finally I download p7zip source, and build 7z with unrar support.
I have the 7z 7z.so Rar.so files from here.
The arch is arm64.

And now everything works !

May be we can pack 7z with arm64 and x86_64, and based on the arch we run, select one or the other.
Or just build 2 packages, one for m1/m2, and one for x86_64 ?

**Comment by celogeek** [comment]
Here the p7zip that works with m1 build.

[bin.zip](https://github.com/darodi/kcc/files/10298874/bin.zip)

**Comment by celogeek** [comment]
Here the p7zip that works with m1 build.

[bin.zip](https://github.com/darodi/kcc/files/10298874/bin.zip)

**Comment by celogeek** [comment]
And here the dmg compatible with m1:
https://static.celogeek.com/KCC/M1/KindleComicConverter_osx_5.5.3b17.dmg

**Comment by darodi** [comment]
@celogeek 

> May be we can pack 7z with arm64 and x86_64, and based on the arch we run, select one or the other. Or just build 2 packages, one for m1/m2, and one for x86_64 ?



Thanks a lot! 
I'll try to adapt the pipeline to use those tools.
I started doing it in this other issue 
- #4 


Merry Christmas!

**Comment by celogeek** [comment]
I put the full process here:
https://github.com/darodi/kcc/issues/4#issuecomment-1364553511

**Comment by celogeek** [comment]
> @celogeek
> 
> > May be we can pack 7z with arm64 and x86_64, and based on the arch we run, select one or the other. Or just build 2 packages, one for m1/m2, and one for x86_64 ?
> 
> Thanks a lot! I'll try to adapt the pipeline to use those tools. I started doing it in this other issue
> 
> * [Kindle Comic Converter - Native Apple Silicon #4](https://github.com/darodi/kcc/issues/4)
> 
> Merry Christmas!

Merry christmas too ;)

I put in this issue how I manage to build and make the too works on my m1.

**Comment by darodi** [comment]
> I put in this issue how I manage to build and make the too works on my m1.

That might be a bit harder with github actions. They don't support Apple M1 hardware, except for self runners.
So cross compilation is needed. 
Last time I was stuck with Qt library but I haven't tried again since then.
Anyway, everything you tried will be needed later in the process.

**Comment by darodi** [comment]
@celogeek 

does this work for you?

https://github.com/darodi/kcc/suites/10042775406/artifacts/488537303

If it does, I'll add it to the pipeline.

**Comment by macandiphone** [comment]
I have the same problem, my intel Mac does not work with the latest version, when I convert the file it prompts an error but the error code is NONE, I try to convert various types of files and I get the same result.

**Comment by darodi** [comment]
closing this.

follow-up in 
- https://github.com/darodi/kcc/issues/4
